---
title: "unemployment and salary"
author: "Shangjun Jiang"
date: "10/7/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(hexbin)
library(corrplot)
library(car)
library(ggplot2)
library(tidyr)
library(reshape2)
library(stringr)
library(readr)
library(readxl)
library(tidyverse)
library(dplyr)


setwd("~/Desktop/jenny-jiang")
```



# UNEMPLOYMENT RATES AND EARNINGS BY EDUCATIONAL ATTAINMENT""
#### load the data 
```{r}

unemploy16 <- read_excel(path = "Unemployment rates and earnings by educational attainment.xlsx", sheet = 1)
unemploy15 <- read_excel(path = "Unemployment rates and earnings by educational attainment.xlsx", sheet = 2)
unemploy14 <- read_excel(path = "Unemployment rates and earnings by educational attainment.xlsx", sheet = 3)
unemploy13 <- read_excel(path = "Unemployment rates and earnings by educational attainment.xlsx", sheet = 4)
unemploy12 <- read_excel(path = "Unemployment rates and earnings by educational attainment.xlsx", sheet = 5)


unemploy12$year <- "2012"
unemploy13$year <- "2013"
unemploy14$year <- "2014"
unemploy15$year <- "2015"
unemploy16$year <- "2016"


colnames(unemploy16) <- c("education", "unemployment rate", "median weekly wage", "year")
colnames(unemploy15) <- c("education", "unemployment rate", "median weekly wage", "year")
colnames(unemploy14) <- c("education", "unemployment rate", "median weekly wage", "year")
colnames(unemploy13) <- c("education", "unemployment rate", "median weekly wage", "year")
colnames(unemploy12) <- c("education", "unemployment rate", "median weekly wage", "year")


all14 <- unemploy14 
all15 <- unemploy15
all16 <- unemploy16


#delete all-year workers
unemploy14 <- unemploy14[unemploy14$education != "All workers",]
unemploy15 <- unemploy15[unemploy15$education != "All workers",]
unemploy16 <- unemploy16[unemploy16$education != "Total",]



### join the dataset
unemploy1516 <-  full_join(unemploy16, unemploy15)
unemploy1416 <- full_join(unemploy1516, unemploy14)
unemploy1316 <- full_join(unemploy1416, unemploy13)
unemploy1216 <- full_join(unemploy1316, unemploy12)

colnames(unemploy1216) <- c("education", "unemloy_rate", "weekly_wage", "year")

#write.csv(unemploy1216,"unemploy1216.csv")


```


### factor 

```{r}
unemploy1216$education <- as.factor(unemploy1216$education)
unemploy1216$year <- as.factor(unemploy1216$year)
str(unemploy1216$education)


```


# EDUCATIONAL ATTAINMENT BY DETAILED OCCUPATION

### load data
```{r}
edu08 <- read_excel(path = "educational attainment by detailed occupation.xlsx", sheet = 1)
edu09 <- read_excel(path = "educational attainment by detailed occupation.xlsx", sheet = 2)
edu1011 <- read_excel(path = "educational attainment by detailed occupation.xlsx", sheet = 3)
edu1213 <- read_excel(path = "educational attainment by detailed occupation.xlsx", sheet = 4)
edu1415 <- read_excel(path = "educational attainment by detailed occupation.xlsx", sheet = 5)


```


## add year to the column

```{r}
edu1415$year <- "2014"
edu1213$year <- "2012"
edu1011$year <- "2010"
edu09$year <- "2009"
edu08$year <- "2008"

colnames(edu1415) <- c("employment", "code", "less hs", "high school", "some college, no degree", "associate", "bachelor", "master", "doctor/professional", "year")

colnames(edu1213) <- c("employment", "code", "less hs", "high school", "some college, no degree", "associate", "bachelor", "master", "doctor/professional", "year")

colnames(edu1011) <- c("employment", "code", "less hs", "high school", "some college, no degree", "associate", "bachelor", "master", "doctor/professional", "year")

colnames(edu09) <- c("employment", "code", "less hs", "high school", "some college, no degree", "associate", "bachelor", "master", "doctor/professional", "year")

#colnames(edu08) <- c("employment", "code", "less hs", "high school", "some college, no degree", "associate", "bachelor", "master", "doctor/professional", "year")


### join the dataset
edu1215 <-  full_join(edu1415, edu1213)
edu1015 <- full_join(edu1215, edu1011)

#write.csv(edu1015,"edu1015.csv")

```


# OCCUPATIONS THAT NEED MORE EDUCATION FOR ENTRY ARE PROJECTED TO GROW FASTER
### load data
```{r}
## Typical entry-level education
"Occupations that Need More Education for Entry are Projected to Grow Faster.xlsx"
edu_level14 <- read_excel(path = "Occupations that Need More Education for Entry are Projected to Grow Faster.xlsx", sheet = 1)
edu_level12 <- read_excel(path = "Occupations that Need More Education for Entry are Projected to Grow Faster.xlsx", sheet = 2)
edu_level10 <- read_excel(path = "Occupations that Need More Education for Entry are Projected to Grow Faster.xlsx", sheet = 3)

edu_level14$year <- "2014"
edu_level12$year <- "2012"
edu_level10$year <- "2010"


edu_level1210 <-  full_join(edu_level10, edu_level12)
edu_level1014 <-  full_join(edu_level14, edu_level1210)
#write.csv(edu_level1014,"edu_level1014.csv")

job_training12 <- read_excel(path = "Occupations that Need More Education for Entry are Projected to Grow Faster.xlsx", sheet = 4)
job_training10 <- read_excel(path = "Occupations that Need More Education for Entry are Projected to Grow Faster.xlsx", sheet = 5)

job_training12$year <- "2012"
job_training10$year <- "2010"

job_training1012 <- full_join(job_training12, job_training10)

#write.csv(job_training1012,"job_training1012.csv")

work_experience12 <- read_excel(path = "Occupations that Need More Education for Entry are Projected to Grow Faster.xlsx", sheet = 6)
work_experience10 <- read_excel(path = "Occupations that Need More Education for Entry are Projected to Grow Faster.xlsx", sheet = 7)

work_experience12$year <- "2012"
work_experience10$year <- "2010"

work_experience1012 <- full_join(work_experience12, work_experience10)


write.csv(work_experience1012,"work_experience1012.csv")



```




# EDUCATION AND TRAINING ASSIGNMENTS BY DETAILED OCCUPATION
### load data

```{r}
edutrain14 <- read_excel(path="Education and training assignments by detailed occupation, 2014.xlsx", sheet=1)
edutrain12 <- read_excel(path="Education and training assignments by detailed occupation, 2014.xlsx", sheet=2)
edutrain10 <- read_excel(path="Education and training assignments by detailed occupation, 2014.xlsx", sheet=3)

edutrain14$year <- "2014"
edutrain12$year <- "2012"
edutrain10$year <- "2010"

edutrain1214 <-  full_join(edutrain14, edutrain12)
edutrain1014 <-  full_join(edutrain10, edutrain1214)

#write.csv(edutrain1014, "edutrain1014.csv")


```


# Employment Projections

```{r}

employ_proj14 <- read_excel(path="-Employment Projections.xlsx", sheet =1)
employ_proj12 <- read_excel(path="-Employment Projections.xlsx", sheet =2)

employ_proj12$year <- "2012"
employ_proj14$year <- "2014"

colnames(employ_proj12) <- c("occupation", "code", "employ1", "employ2", "change_number", "change_percent", "job_change_number", "annual_wage", "education", "work_experience", "job_training", "year")
colnames(employ_proj14) <- c("occupation", "code", "employ1", "employ2", "change_number", "change_percent", "job_change_number", "annual_wage", "education", "work_experience", "job_training", "year")


employ_proj1214 <-  full_join(employ_proj14, employ_proj12)

#write.csv(employ_proj1214, "employ_proj1214.csv")



```



























