---
title: "Load data + draw plots"
author: "Shangjun Jiang"
date: "12/3/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## load libaries 
require(MASS)
library(hexbin)
library(corrplot)
library(car)
library(ggplot2)
require(methods)
require("leaps")
library(tidyr)
library(reshape2)
library(ridge)
require(lars)
library(descr)
library(stringr)
library(readr)
library(readxl)
library(tidyverse)
#library(plyr)
library(dplyr)


library(htmlwidgets)
library(ggiraph)

library(highcharter)
library(RColorBrewer)
library(flexdashboard)
library(leaflet)
library(scatterD3)
library("billboarder")
library(rbokeh)
library(metricsgraphics)


# set work directory  Please change this
setwd("~/Desktop/jenny-jiang")

```



```{r}
### load data
emp_edu_salary_1015 <- read.csv("clean_data/ALL_emp_edu_salary_1015.csv")
emp_edu_salary_1015$X <- NULL


#colnames(emp_edu_salary_1015)[11:17] <- c("less hs", "high school", "some college, no degree", "associate", "bachelor", "master", "doctor/professional")


### wide to long format 
melt1015 <- melt(emp_edu_salary_1015, 
     measure.vars = c("less.hs", "high.school", "associate", "some.college..no.degree", "bachelor", "master", "doctor.professional"), 
     variable.name = "degrees", 
     value.name = "number")

#aggregate degree variables
melt1015$edu <- melt1015$degrees


# college +
levels(melt1015$edu)[levels(melt1015$edu)=="bachelor"] <- "college+"
levels(melt1015$edu)[levels(melt1015$edu)=="doctor.professional"] <- "college+"
levels(melt1015$edu)[levels(melt1015$edu)=="master"] <- "college+"

# hs - college
levels(melt1015$edu)[levels(melt1015$edu)=="some.college..no.degree"] <- "hs-college"
levels(melt1015$edu)[levels(melt1015$edu)=="associate"] <- "hs-college"

# hs -
levels(melt1015$edu)[levels(melt1015$edu)=="high.school"] <- "hs-"
levels(melt1015$edu)[levels(melt1015$edu)=="less.hs"] <- "hs-"


melt1015$total_number <- NULL
melt1015$men_number <- NULL
melt1015$women_number <- NULL


melt1015$year <- as.factor(melt1015$year)
melt1015$code <- as.factor(melt1015$code)


colnames(melt1015)[colnames(melt1015) == "median"] <- "median_age"
colnames(melt1015)[colnames(melt1015) == "total_median"] <- "median_salary"

head(melt1015)


#melt1015$job <- gsub(' managers','',melt1015$employment)


## aggregate to get the total number for every jobs
total_summary_num <- melt1015 %>%
  group_by(year, employment) %>%
  summarize(sum_number=sum(number, na.rm=T))


## aggregate to get the total number of employment by detailed education. 
total_summary_degrees <- melt1015 %>%
  group_by(year, employment,edu) %>%
  summarize(sum_number=sum(number, na.rm=T))

#write.csv(total_summary_degrees, "total_summary_degrees.csv")


#make a copy of the dataset
everything <- melt1015

#only filter the total number
total_sum1 <-melt1015 %>% 
  filter(melt1015$employment == "Total, all occupations")

write.csv(total_sum1, "overview_total.csv")

# aggregate by year and edu
total_sum_degree1 <- total_sum1 %>% 
  group_by(year, edu) %>% 
  summarize(sum_number = sum (number, na.rm = T))

# delete the total number, only left with detailed number. 
melt1015 <- melt1015 %>% 
  filter(melt1015$employment != "Total, all occupations")

write.csv(melt1015, "total1015.csv")



#aggregate by year and edu
total_sum_degree <- melt1015 %>% 
  group_by(year, edu) %>% 
  summarize(sum_number = sum (number, na.rm = T))



```


### Divide by different industries 

```{r}

### the rest of the industry
melt1015_other <- melt1015[grepl("-", melt1015$code),]

melt1015_other$indus <- str_extract_all(melt1015_other$code2, "[0-9]{2}-")

melt1015_other$indus <- str_extract_all(melt1015_other$indus, "[0-9]{2}")

melt1015_other$indus <- as.numeric(melt1015_other$indus)
melt1015_other$indus <- as.factor(melt1015_other$indus)


industry_22 <- melt1015_other %>% 
  group_by(indus,year,edu) %>% 
  summarize(sum_num=sum(number, na.rm = T))


sum_22 <- merge(x = industry_22, y = codebook, by = "indus", all.x = TRUE)



object <- ggplot(sum_22, aes(x=sum_num, y=employment, frames=year), alpha=0.5) +
  geom_point(aes(color=edu)) +
  geom_point(aes(x=0, y=employment, size=median_salary))


gganimate(object)


melt1015_other <- melt1015_other[!duplicated(melt1015_other$indus),]


## 22 industry
melt1015_22 <- melt1015[!grepl("-", melt1015$code),]

melt1015_other$indus <- str_extract_all(melt1015_other$code2, "[0-9]{2}-")

melt1015_other <- unique(melt1015_22$indus)






years %>% str_match_all("[0-9]+") %>% unlist %>% as.numeric

?str_match_all
melt1015_22$code2 %>% 
  str_match_all(melt1015_22$code2, "[0-9]{2}-")





gsub("", "[0-9]{2}-", melt1015$code2)


melt1015[grepl("[0-9]{2}-", melt1015$code2),]

m <- gregexpr("[0-9][0-9]-", melt1015$code2)

regmatches(melt1015$code2, m)


```




### PLOT


```{r}
# define a ColorBrewer palette
cols <- brewer.pal(7, "Set1")

# make chart
edu_chart <- hchart(total_sum_degree1, "line", hcaes(x = year, y = sum_number, group = edu)) %>%
  hc_colors(cols) %>%
  hc_chart(style = list(fontFamily = "Georgia",
                        fontWeight = "bold")) %>%
  hc_xAxis(title = list(text="Year")) %>%
  hc_yAxis(title = list(text="Total Number of Workers")) %>%
  hc_plotOptions(series = list(marker = list(enabled = TRUE, symbol = "circle"))) %>% 
  hc_title(text="Total number of workers by educational level in 2010-2015")

# plot chart
print(edu_chart)

# save as a web page
saveWidget(edu_chart, "total_edu.html", selfcontained = TRUE, libdir = NULL, background = "white")



```





```{r}
total_summary <- melt1015 %>%
  group_by(year, edu,job) %>%
  summarize(sum =sum(number, na.rm=T))

ggplot(melt1015, aes(x=median_salary, y=number)) + geom_point()


object <- 

  
ggplot(melt1015, aes(x=number, y=employment), alpha=0.5) +
  geom_point(aes(color=edu)) +
  geom_point(aes(x=0, y=employment, size=median_salary))

gganimate(object)

# a different dataset, 
# DATASET 1: numbers by year and by educational level and job 
# DATASET 2: median salary by year and job. aggregate data. 

size=median_salary, x=median_salary, y=0,


```




